server:
  port: 8000
spring:
  application:
    name: zuulservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
zuul:
  routes:
    api-a:
      path: /sharinglife/**
      serviceId: sharinglife

    api-b:
      path: /sharinglife1/**
      serviceId: ssharinglife




